print('Well hey there!')
print('Whats your name, hotshot?')
myName = input()
print('Well mighty fine to meet you, ' + myName)
print('Im ol man gobblegon!')
print('If my countin is right the length of yoru name is ')
print(len(myName))
print('How old are you again?')
myAge = input()
print('Ahh thats right you are ' + myAge)
print('looks like youll be ' + str(int(myAge) + 1) + ' in a years time!')